apiVersion: v1
kind: Service
metadata:
  name: ci-cd-service
spec:
  selector:
    app: ci-cd-app
  ports:
    - protocol: TCP
      port: 80        # external port for clients
      targetPort: 8080 # port on the container
  type: LoadBalancer
